### ISSUE TITLE
various issues with w1:adder writeup

### ISSUE THREAD

**Issue by duanwilliam** [ucsd-compilers-s23/ucsd-compilers-s23.github.io#4]
there are several typos/omissions in the code/commands of the writeup. not sure if all the code provided in the tutorial is expected to work or if students are expected to debug issues they do encounter when copying over the code in the tutorial part of the writeup, so not sharing issues/fixes yet; but can submit PR with fixes if all the code in the tutorial is expected to work.

for instance, a trivial case that is just a minor typo and not coding/debugging related: in the "Generating Assembly" section, involving the `37` test, the writeup says to run `cat test.367.s`, whereas it should say `cat test/37.s`.

**Comment by jpolitz** [comment]
Thanks, what are the others?

**Comment by duanwilliam** [comment]
- "more sophisticated `main`" doesn't have the relevant std imports (e.g. `File` needs a `use std::fs::File;`)
- makefile tab size right now is 2 spaces, which didn't work for me (had to change to 4)
- there's a misplaced comma after the `Sexp::List` match statement in `parse_expr` (it's one layer too deep, should be after the braces for `Sexp::List`)
- `compile_expr` should append a newline before appending the asm `add`/`sub` instruction string
- subjective, but I believe trailing commas (e.g. for `Expr::Sub1`) are part of Rust's recommended style guide (and I believe rustfmt adds trailing commas by default as well)
